#!/usr/bin/env bash
set -e

current_version="$1"
tmp="$(mktemp -d)"
cd "$tmp"
git init -q
git remote add origin https://github.com/Zygo/bees.git
git fetch --depth=200 --tags -q origin 2>/dev/null
git checkout -q FETCH_HEAD
upstream_version="$(git describe --always --dirty | sed 's/^[vV]//')"
cd / && rm -rf "$tmp"

[ "$upstream_version" != "$current_version" ]
