#!/usr/bin/env bash
set -e

current_version="$1"
tmp="$(mktemp -d)"
git clone --filter=blob:none https://github.com/Zygo/bees.git "$tmp" 2>/dev/null
cd "$tmp"
upstream_version="$(git describe --always --dirty | sed -E 's/^[a-zA-Z]//')"
cd / && rm -rf "$tmp"

[ "$upstream_version" != "$current_version" ]
