#!/usr/bin/env bash
set -e

tmp="$(mktemp -d)"
git clone --filter=blob:none https://github.com/Zygo/bees.git "$tmp" 2>/dev/null
cd "$tmp"
version="$(git describe --always --dirty | sed -E 's/^[a-zA-Z]//')"
echo "version=$version"
echo "---"
git log --oneline -20
cd / && rm -rf "$tmp"
