#!/usr/bin/env bash
set -e

current_version="$1"
tag=$(gh api repos/rvaiya/keyd/tags --jq '.[0].name' 2>/dev/null || echo "unknown")
sha=$(gh api repos/rvaiya/keyd/commits/HEAD --jq '.sha' 2>/dev/null || echo "")
ahead=$(gh api "repos/rvaiya/keyd/compare/$tag...HEAD" --jq '.ahead_by' 2>/dev/null || echo "0")
upstream_version="$(echo "$tag" | sed -E 's/^[a-zA-Z]//')-$ahead-g$(echo "$sha" | cut -c1-7)"

[ "$upstream_version" != "$current_version" ]
